### ISSUE TITLE
Bot won't work

### ISSUE THREAD

**Issue by Sushi1i** [citharus/What-should-I-read#2]
For some reason the bot is offline and the commands won't work

**Comment by citharus** [comment]
I hosted the bot on Heroku, which means it runs only a limited time without money. I did not expect interest in the bot so I abandoned the project. If you're still interested I'll look for a new hosting method.

**Comment by citharus** [comment]
It should be running again by now

**Comment by Sushi1i** [comment]
Thanks very much! I appreciate it!

I'm sorry about people didn't take interest! I hope you find a hosting
method that works for you!
